---
# tasks file for db
- name : Update Repository
  apt :
    update-cache: yes
 
- name : Install packages required
  apt : 
    name : "{{ packages }}"
    state : present
  

- name: Update mysql root password for all root accounts
  mysql_user: name=root password={{ db_password }}  priv="*.*:ALL,GRANT"

- name : Copy config file
  template :
     src : .my.cnf.j2
     dest : /root/.my.cnf
     owner : root
     group : root
     mode : 0600
  notify :
        - restart mysql

    
