---
# tasks file for db
- name : Update Repository
  apt :
    update : yes
    
    
- name : Install packages required
  apt : 
    name : {{ item }}
    state : present
    with-items :
      - PyMySQL
      - mysql-server
    update-cache : yes

- name : Configure database user 
  mysql_user : 
    name : db_user
    password : passwd
    priv : '*.*:ALL'
    state : present
    
