---
- name : Install protoc compiler
  command : snap install protobuf --classic

- name : Create directories for packages
  file :
    state : directory
    mode : 0644
    owner : root
    group : root
    path : /root/go

- set_fact : 
    go_path : "{{ lookup('env', 'GOPATH') | default(ansible_env.HOME+'/go', true) }}"

- name : Install packages required
  command : "/usr/local/go/bin/go get -u {{ item }}"
  environment :
      GOPATH : "{{ go_path }}"
  with_items :
          - "google.golang.org/grpc"
          - "github.com/golang/protobuf/protoc-gen-go"
